apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-secrets-with-username-password
spec:
  background: false
  rules:
  - name: deny-secrets-with-username-password
    match:
      resources:
        kinds:
        - Secret
    validate:
      message: "Secrets containing both 'username' and 'password' fields are not allowed."
      pattern:
        spec:
          data:
            username: "[a-zA-Z0-9+/=]+"
            password: "[a-zA-Z0-9+/=]+"
      anyPattern: true
      deny: {}
