apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-secrets-with-username-password
spec:
  validationFailureAction: audit
  background: false
  rules:
  - name: deny-secrets-with-username-password
    match:
      resources:
        kinds:
        - Secret
    validate:
      message: "Secrets containing both 'username' and 'password' fields are not allowed."
      pattern:
        data:
          username: "*"
          password: "*"
      anyPattern: true
      deny: {}
