apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-secrets-with-username-password
  annotations:
    policies.kyverno.io/title: Restrict Secrets by Name
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: Pod, Secret
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.21"
    policies.kyverno.io/description: >-
      Restrict username and password in secret
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: deny-secrets-with-username
    match:
      resources:
        kinds:
        - Secret
    validate:
      message: username not allowed.
      pattern:
        =(data):
          - (name): "username"
            value: "null"
  - name: deny-secrets-with-password
    match:
      resources:
        kinds:
        - Secret
    validate:
      message: password not allowed.
      pattern:
        =(data):
          - (name): "password"
            value: "null"

      
