apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-secrets-with-username-password
  annotations:
    policies.kyverno.io/title: Restrict Secrets by Name
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: Pod, Secret
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.21"
    policies.kyverno.io/description: >-
      Restrict username and password in secret
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-secrets
    match:
      any:
      - resources:
          kinds:
          - Secret
    validate:
      message: "Cannot define username and password in secret"
      pattern:
        data:
          username: null
          password: null

      
